### ISSUE TITLE
Should we encourage the use of virtual environments?

### ISSUE THREAD

**Issue by pajlada** [pajlada/pajbot#122]
http://stackoverflow.com/questions/23842713/using-python-3-in-virtualenv/23842752#23842752
or
http://stackoverflow.com/a/30233408

**Comment by KostasPelelis** [comment]
The main advantage of virtual environment is scalability and independence. For example if a library you are using (e.g. Flask) decides to upgrade some stuff you can just create a new virtual env and test things out, while you have an environment that everything runs smoothly.

**Comment by hptk** [comment]
Virtual environments are great, and I suggest recommending the use of them. I have myself only used virtualenv, not venv, and I have great experience with it. The only downside with virtualenv is that the activation scripts are written in bash script so you have to use a shell which supports that (I use fish, and have to start a bash-session for virtualenv, kinda cluky).

**Comment by Nacht123** [comment]
I tested __virtualenv__
it was way easier to install the pip modules in Ubuntu with virtualenv.


I updated the [Guide](/pajlada/pajbot/wiki/Installation-Bot) for the Bot and added __virtualenv__


If you want to use __venv__ instead, it's almoste the same way to install it.

**Comment by Nacht123** [comment]
since you use **venv** now

i have some suggestions for **venvinstall.sh**
```bash
#!/bin/bash
pyvenv-3.4 myvenv
source myvenv/bin/activate
pip install -r pip-requirements.txt
```

# move **venvinstall.sh** to **/install**

change the file to
```bash
#!/bin/bash
cd ../
pyvenv-3.4 myvenv
source myvenv/bin/activate
pip install -r pip-requirements.txt
```

# and maybe update **pip** in it
```bash
#!/bin/bash
cd ../
pyvenv-3.4 myvenv
source myvenv/bin/activate
pip install pip --upgrade
pip install -r pip-requirements.txt
```
If I use **pip 1.5.6** it stuck at some point.
At this point you don't know if its still working or if it's crashed :imp:
and the install looks ugly

when it stuck
![stuck](http://i.imgur.com/GzPWWFs.png)

**pip 8.0.2 vs 1.5.6** at the end
**8.0.2** looks clean | **1.5.6** looks ugly
![pip](http://i.imgur.com/rKNgGEO.png)
