### ISSUE TITLE
Choose what emotes to use

### ISSUE THREAD

**Issue by gigglearrows** [pajlada/pajbot#130]
Add a module that lets you choose different emotes for commands.
For example, set champ_emote = 'PogChamp' for one channel, but champ_emote = 'forsenChamp' on another one. and then use the variable champ_emote instead in the commands that uses this emote. Set default as 'PogChamp'.

Can also add stuff like: 
thump_emote = 'BibleThump' or thump_emote = 'anniesThump'
gasm_emote = 'Kreygasm' or gasm_emote='gachiGasm'

**Comment by pajlada** [comment]
I think the proper way to do this is give the player ability to change the exact message that's used instead.

So for the !duel command for example we can provide the `{} won the duel vs {} PogChamp` string that people can change

**Comment by gigglearrows** [comment]
True :)

**Comment by Nacht123** [comment]
I tried something, I'm not sure if that's the best way.
Because there is always a duplicate for the error message in the code.

## Part of the code [git diff]
![code](http://i.imgur.com/RdMt8vH.png)

## Settings
You can change the __first message__ and the __second message__
![Settings](http://i.imgur.com/3LVOoH3.png)

## Examples
![examples](http://i.imgur.com/r65J393.png)

## Error in Settings
__The bad part about this is, the level 500 MOD can make errors to the code.__
![errors](http://i.imgur.com/bkU4ItV.png)

## Error message
__Should there be an error message or just a default message?__
![errormessage](http://i.imgur.com/23eDTvk.png)

<br/><br/><br/>
__**Or maybe there is a different better way to do it**__ :dancers:

**Comment by pajlada** [comment]
Basic system implemented in 04730ec275bcf2b32dc8449958c9dba908d7b945 thanks to @Nacht123 

More modules should use this. Can be used for whisper-shit as well.

**Comment by pajlada** [comment]
Closing this issue, as the general discussion has been had already.
Now it's only a matter of doing this in all relevant modules.
