### ISSUE TITLE
!#showemote optional arguments X and Y

### ISSUE THREAD

**Issue by pajlada** [pajlada/pajbot#156]
So you can decide exactly where the emote should be shown in chat.

Point bounty: 3000

**Comment by Nacht123** [comment]
it's more **funny**, if it's **random** on his face and **not rigged** :skull:

**Comment by pajlada** [comment]
Agreed

**Comment by CodeBowser** [comment]
Imo it would be better if the emote is not shown in bottom corner or somewhere else where it can't be seen. Like what about setting a border/specified area where emotes are shown and where not would be cool. Because it's kinda sad when you spent a token and then you can't see if because it's on the g2a logo or something

**Comment by pajlada** [comment]
Yeah I don't think I want this feature. The emote bounding boxes could be smart, but idk exactly how that should be implement. That's like ultra super low prio, so I'll just close this.
