### ISSUE TITLE
point bounty

### ISSUE THREAD

**Issue by pajlada** [pajlada/pajbot#157]
I'm considering giving points for people helping me out with the bot

 * well-described bug report in an issue: 1000 points
 * a good idea: 500-1500 points (depending on how good the idea is)
 * sending a PR with working code: 1000+ points (depends on the size of the PR)

you can chose whether to get the points in forsens or my chat
thoughts?

**Comment by Lumiare1** [comment]
I think it's fine; they'll gamba all their pleb points away anyway 4Head

Only thing is I would suggest giving them more options than just your or Forsen's chat; someone might want points in one of your other bots.

**Comment by T-Brawl** [comment]
- Convert donation to points (1 dollar = 100 points) ?
- !duel <username> all (like you did yesterday with !roulette all) ?
- Possibility for subs to give points to someone with a tax (30% tax) ?
- Duel with losing getting timeout ?

I dunno Kev

**Comment by pajlada** [comment]
@T-Brawl !givepoints is implemented. i don't think i want tax on point transfers though
donation to points is a no-no
!duel all is trickier since there's a limit for how many points you can duel

**Comment by Bassofia** [comment]
- Customizable ranking system(Let the admin add rankings and point/hour requirements) based on how many points the user has or how many hours it has spent in the channel.

- Traslation/bot output customization interface to modify commands (ex: Name your points "keks" so instead of points it's !keks) and bot messages. Maybe in the config file (????).

- BabyRage Windows Install Guide BabyRage (Maybe a how to emulate ubuntu in windows in case native windows install is impossible).

Any link to the current bot features to think of more?

**Comment by pajlada** [comment]
I think the only place where the name "points" is fully hard-coded is on the website, where it links to the /points/ page etc.
When you add your own command to check how many points the user has, you could just do this:
`!add command keks $(usersource;1:username_raw) has $(usersource;1:points) keks xD`
