### ISSUE TITLE
Check how long a viewer has been watching the stream

### ISSUE THREAD

**Issue by kritzware** [pajlada/pajbot#214]
Possible to do something like `!uptime`, but with a user parameter? e.g. `!uptime kritzware`, this then returns, `"kritzware, you have been watching the stream for 2 hours etc."`

**Comment by dextermb** [comment]
You would have to start tracking when a user enters the channel compared to the time when they run the command

```
user joins -> store (date)time -> user runs command -> compares current (date)time to stored (date)time
```

Not sure how much strain this would put on the bot(s) though.

**Comment by kritzware** [comment]
I was thinking of that same method @dextermb, but like you said, it depends how much extra strain it might put on the bots.

**Comment by pajlada** [comment]
My way of solving this would be to keep a dictionary in the User object called time_spent_in_stream.
The key would be the current stream ID, and every time minutes_in_chat_online is increment, we increment the time_spent_in_strema[stream_id] by 5 as well.
There's no way to make this super-exact, since we can't rely on a lot of the data that twich is giving us.
