### ISSUE TITLE
Checking rustlelogs in different month than the current one

### ISSUE THREAD

**Issue by ShiniXi** [pajlada/pajbot#271]
Hi xD
Had a little suggestion for the !rustlelogs command
Basically you can enter month along with year and it finds the chat logs for that month.
Usage could be for example:
`!rustlelogs ShiniXi <month> <year>`
`!rustlelogs ShiniXi january 2016`
and the result given would be:
`Snusbot: overrustlelogs.net/Forsenlol%20chatlog/<month>%20<year>/userlogs/shinixi.txt`
`Snusbot: overrustlelogs.net/Forsenlol%20chatlog/January%202016/userlogs/shinixi.txt`
I don't know if this would be hard to make, just think it would be a nice feature.
Also first time using this website gachiGASM

**Comment by Nacht123** [comment]
Most of the time you just want to check the last logs of a person.
If the log is empty you change the **month manually**.

If a user is banned the best way to find the last log is
`!lastseen USERNAME` and check the logs for this date.

But yeah since overrustlelogs is only there for a **few channels**,
it is not worth it for a new feature, than it will not really be used.

`!rustlelogs` is **already** always the **last log** for the current month.

**Comment by Nacht123** [comment]
closing this, read the other comment for more details :ghost:
