### ISSUE TITLE
ImportError: No module named 'irc'

### ISSUE THREAD

**Issue by Leafpad** [pajlada/pajbot#327]
Hello,
this is probably a really easy-to-solve issue but I seriously can't figure it out myself. I've done everything in the installation guide (using Ubuntu 17.04 in a VM) but when I do: 
sudo ./main.py --config configs/pajbot.ini

I get this error:
Traceback (most recent call last):
  File "./main.py", line 7, in <module>
    from pajbot.bot import Bot
  File "/srv/pajbot/pajbot/bot.py", line 10, in <module>
    import irc.client
ImportError: No module named 'irc'

I'd appreciate any help.

**Comment by pajlada** [comment]
If the module irc can't be found it's either due because
1. You're not sourced into the virtual environment
2. You didn't run `./venvinstall.sh`

Also, as a side not, you shouldn't be running the bot with sudo

Let me know if it's still an issue

**Comment by Leafpad** [comment]
Thank you for your reply! I just did ./vensinstall.sh again and obviously sourced into the venv. If I try to start ./main.py without sudo I get the error: "sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1045, "Access denied for user 'root'@'localhost' (using password: NO)")".
With sudo in front ./main.py though I get the irc error.

**Comment by pajlada** [comment]
The "can't find module irc" error is an earlier error than the sql error.
The reason you get that even though you have the module installed is
because you use sudo. Using sudo makes it so you're not sourced into the
virtual environment.

The sql error is what we want to fix.
In the config file your sql string doesn't match up with the credentials in
your mysql password. In the installation guide there's a step where you
create a mysql database and a mysql user. It's that information you need to
use to fill up the config file.

Let me know if this works!


On Apr 20, 2017 01:54, "Leafpad" <notifications@github.com> wrote:

Thank you for your reply! I just did ./vensinstall.sh again and obviously
sourced into the venv. If I try to start ./main.py without sudo I get the
error: "sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError)
(1045, "Access denied for user 'root'@'localhost' (using password: NO)")".
With sudo in front ./main.py though I get the irc error.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/pajlada/pajbot/issues/327#issuecomment-295499650>, or mute
the thread

**Comment by Leafpad** [comment]
Yes you were obviously right. I forgot to change that in the config file. Now I get the error 
"[2017-04-21 17:47:05,244] [ERROR  ] Unhandled HTTP error code"
and at the end 
"urllib.error.HTTPError: HTTP Error 400: Bad Request"

If those are just stupid or easy-to-solve questions then I obviously understand if you don't want to help me any further! I don't want to waste your time :)

**Comment by pajlada** [comment]
Error 400 might be because of missing or bad client_id

Make sure your config files client ids  are filled in

On Apr 22, 2017 03:59, "Leafpad" <notifications@github.com> wrote:

Yes you were obviously right. I forgot to change that in the config file.
Now I get the error
"[2017-04-21 17:47:05,244] [ERROR ] Unhandled HTTP error code"
and at the end
"urllib.error.HTTPError: HTTP Error 400: Bad Request"

If those are just stupid or easy-to-solve questions then I obviously
understand if you don't want to help me any further! I don't want to waste
your time :)

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/pajlada/pajbot/issues/327#issuecomment-296335892>, or mute
the thread

**Comment by pajlada** [comment]
Assuming this is fixed, please re-open if it's not
